/*********************************************************************
 *
 *  TodoListManager - Open-source manager of todo lists
 *
 *  Copyright (C) 2019
 *
 *  This file is part of TodoListManager.
 *
 *  TodoListManager is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  TodoListManager is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with Treeler.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Contact: Lluís Alemany Puig (lluis.alemany.puig@gmail.com)
 *
 ********************************************************************/

package gui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.Timer;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JTree;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.TreeSelectionModel;

import todomanager.task.*;
import todomanager.util.Logger;

/**
 * @brief Main class: the only file that defines the Graphical User Interface.
 * @author Lluís Alemany Puig
 */
public class MainView extends javax.swing.JFrame {

	private DefaultTreeModel treeModel;
	private DefaultMutableTreeNode highPriorNode;
	private DefaultMutableTreeNode medPriorNode;
	private DefaultMutableTreeNode lowPriorNode;
	private Logger log;
	private boolean changesSaved = true;
	
	/**
	 * Creates new form MainView
	 */
	public MainView() {
		log = Logger.getInstance();
		log.begin();
		log.info("Program executed from path: " + System.getProperty("user.dir"));
		
		initComponents();
		
		treeModel = (DefaultTreeModel) (treeTasks.getModel());
		DefaultMutableTreeNode root = (DefaultMutableTreeNode) treeModel.getRoot();
		highPriorNode = (DefaultMutableTreeNode) root.getChildAt(0);
		medPriorNode = (DefaultMutableTreeNode) root.getChildAt(1);
		lowPriorNode = (DefaultMutableTreeNode) root.getChildAt(2);
		
		treeTasks.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
		
		CustomTreeCellRenderer renderer = new CustomTreeCellRenderer(14);
		treeTasks.setCellRenderer(renderer);
		setChangesSaved();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new JPanel();
        jScrollPane6 = new JScrollPane();
        treeTasks = new JTree();
        jPanel2 = new JPanel();
        buttonRemoveTask = new JButton();
        buttonNewTask = new JButton();
        buttonTaskDown = new JButton();
        buttonTaskUp = new JButton();
        buttonIncrPriority = new JButton();
        buttonDecrPriority = new JButton();
        buttonOverwriteTasks = new JButton();
        buttonSaveTasksAs = new JButton();
        buttonExpandAll = new JButton();
        buttonContractAll = new JButton();
        labelUnsavedChanges = new JLabel();
        textBoxError = new JTextField();
        jPanel7 = new JPanel();
        jPanel5 = new JPanel();
        buttonTaskWorking = new JButton();
        buttonTaskCancel = new JButton();
        buttonTaskDone = new JButton();
        buttonTaskDelete = new JButton();
        buttonTaskOnRevision = new JButton();
        buttonTaskHold = new JButton();
        buttonTaskPendingRevision = new JButton();
        buttonEditTask = new JButton();
        buttonClear = new JButton();
        jPanel1 = new JPanel();
        labelTaskState = new JLabel();
        textBoxTaskDate = new JTextField();
        labelTaskID = new JLabel();
        textBoxTaskName = new JTextField();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jScrollPane1 = new JScrollPane();
        textAreaTaskChanges = new JTextArea();
        jLabel3 = new JLabel();
        jLabel6 = new JLabel();
        jScrollPane7 = new JScrollPane();
        textAreaTaskDescription = new JTextArea();
        jLabel4 = new JLabel();
        jMenuBar1 = new JMenuBar();
        jMenu1 = new JMenu();
        menuItemOpenFile = new JMenuItem();
        menuItemAbout = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Todo List Manager");
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        DefaultMutableTreeNode treeNode1 = new DefaultMutableTreeNode("Tasks");
        DefaultMutableTreeNode treeNode2 = new DefaultMutableTreeNode("High Priority");
        treeNode1.add(treeNode2);
        treeNode2 = new DefaultMutableTreeNode("Medium Priority");
        treeNode1.add(treeNode2);
        treeNode2 = new DefaultMutableTreeNode("Low Priority");
        treeNode1.add(treeNode2);
        treeTasks.setModel(new DefaultTreeModel(treeNode1));
        treeTasks.setRootVisible(false);
        treeTasks.addTreeSelectionListener(new TreeSelectionListener() {
            public void valueChanged(TreeSelectionEvent evt) {
                treeTasksValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(treeTasks);

        buttonRemoveTask.setText("Remove");
        buttonRemoveTask.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonRemoveTaskMouseClicked(evt);
            }
        });

        buttonNewTask.setText("New Task");
        buttonNewTask.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonNewTaskMouseClicked(evt);
            }
        });

        buttonTaskDown.setText("Down");
        buttonTaskDown.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonTaskDownMouseClicked(evt);
            }
        });

        buttonTaskUp.setText("Up");
        buttonTaskUp.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonTaskUpMouseClicked(evt);
            }
        });

        buttonIncrPriority.setText("+ Priority");
        buttonIncrPriority.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonIncrPriorityMouseClicked(evt);
            }
        });

        buttonDecrPriority.setText("- Priority");
        buttonDecrPriority.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonDecrPriorityMouseClicked(evt);
            }
        });

        buttonOverwriteTasks.setText("Overwrite");
        buttonOverwriteTasks.setEnabled(false);
        buttonOverwriteTasks.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonOverwriteTasksMouseClicked(evt);
            }
        });

        buttonSaveTasksAs.setText("Save As");
        buttonSaveTasksAs.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonSaveTasksAsMouseClicked(evt);
            }
        });

        buttonExpandAll.setText("Show all");
        buttonExpandAll.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonExpandAllMouseClicked(evt);
            }
        });

        buttonContractAll.setText("Hide all");
        buttonContractAll.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonContractAllMouseClicked(evt);
            }
        });

        labelUnsavedChanges.setText("Unsaved changes");
        labelUnsavedChanges.setEnabled(false);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonExpandAll, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonNewTask, GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(buttonRemoveTask, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(buttonTaskUp, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTaskDown, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonContractAll, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(buttonDecrPriority, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonIncrPriority, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSaveTasksAs, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonOverwriteTasks, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelUnsavedChanges, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNewTask)
                    .addComponent(buttonIncrPriority)
                    .addComponent(buttonTaskUp)
                    .addComponent(buttonOverwriteTasks))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTaskDown)
                    .addComponent(buttonDecrPriority)
                    .addComponent(buttonRemoveTask)
                    .addComponent(buttonSaveTasksAs))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExpandAll)
                    .addComponent(buttonContractAll)
                    .addComponent(labelUnsavedChanges))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6)
                    .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, GroupLayout.PREFERRED_SIZE, 617, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonTaskWorking.setText("Working");
        buttonTaskWorking.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonTaskWorkingMouseClicked(evt);
            }
        });

        buttonTaskCancel.setText("Cancel");
        buttonTaskCancel.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonTaskCancelMouseClicked(evt);
            }
        });

        buttonTaskDone.setText("Done");
        buttonTaskDone.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonTaskDoneMouseClicked(evt);
            }
        });

        buttonTaskDelete.setText("Delete");
        buttonTaskDelete.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonTaskDeleteMouseClicked(evt);
            }
        });

        buttonTaskOnRevision.setText("On revision");
        buttonTaskOnRevision.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonTaskOnRevisionMouseClicked(evt);
            }
        });

        buttonTaskHold.setText("Put on Hold");
        buttonTaskHold.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonTaskHoldMouseClicked(evt);
            }
        });

        buttonTaskPendingRevision.setText("Pending revision");
        buttonTaskPendingRevision.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonTaskPendingRevisionMouseClicked(evt);
            }
        });

        buttonEditTask.setText("Edit Task");
        buttonEditTask.setEnabled(false);
        buttonEditTask.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonEditTaskMouseClicked(evt);
            }
        });

        buttonClear.setText("Clear");
        buttonClear.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                buttonClearMouseClicked(evt);
            }
        });

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(buttonTaskWorking, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTaskDone, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTaskHold, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(buttonTaskPendingRevision, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTaskOnRevision, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEditTask, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(buttonTaskCancel, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTaskDelete, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClear, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTaskDone)
                    .addComponent(buttonTaskOnRevision)
                    .addComponent(buttonTaskCancel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTaskPendingRevision)
                    .addComponent(buttonTaskDelete)
                    .addComponent(buttonTaskWorking))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTaskHold)
                    .addComponent(buttonEditTask)
                    .addComponent(buttonClear))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelTaskState.setHorizontalAlignment(SwingConstants.CENTER);
        labelTaskState.setText("-");

        textBoxTaskDate.setEditable(false);

        labelTaskID.setHorizontalAlignment(SwingConstants.CENTER);
        labelTaskID.setText("000000");

        textBoxTaskName.setEditable(false);

        jLabel1.setText("Name");

        jLabel2.setText("Date");

        textAreaTaskChanges.setEditable(false);
        textAreaTaskChanges.setColumns(20);
        textAreaTaskChanges.setLineWrap(true);
        textAreaTaskChanges.setRows(5);
        jScrollPane1.setViewportView(textAreaTaskChanges);

        jLabel3.setText("Description");

        jLabel6.setText("id:");

        textAreaTaskDescription.setEditable(false);
        textAreaTaskDescription.setColumns(20);
        textAreaTaskDescription.setLineWrap(true);
        textAreaTaskDescription.setRows(8);
        textAreaTaskDescription.setTabSize(4);
        jScrollPane7.setViewportView(textAreaTaskDescription);

        jLabel4.setText("History");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(textBoxTaskName)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTaskID, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(textBoxTaskDate)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTaskState, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(textBoxTaskName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTaskID)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(textBoxTaskDate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(labelTaskState, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 332, GroupLayout.PREFERRED_SIZE)))
        );

        GroupLayout jPanel7Layout = new GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        menuItemOpenFile.setText("Open");
        menuItemOpenFile.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                menuItemOpenFileMousePressed(evt);
            }
        });
        jMenu1.add(menuItemOpenFile);

        menuItemAbout.setText("About");
        menuItemAbout.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                menuItemAboutMousePressed(evt);
            }
        });
        jMenu1.add(menuItemAbout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(textBoxError)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 419, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBoxError, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void setNodeExpandedState(DefaultMutableTreeNode node, boolean expanded) {
		ArrayList<DefaultMutableTreeNode> list = Collections.list(node.children());
		for (DefaultMutableTreeNode treeNode : list) {
			setNodeExpandedState(treeNode, expanded);
		}
		if (!expanded && node.isRoot()) {
			return;
		}
		TreePath path = new TreePath(node.getPath());
		if (expanded) {
			treeTasks.expandPath(path);
		}
		else {
			treeTasks.collapsePath(path);
		}
	}
	
	private void setTreeExpandedState(boolean expanded) {
		DefaultMutableTreeNode node = (DefaultMutableTreeNode) treeTasks.getModel().getRoot();
		setNodeExpandedState(node, expanded);
	}
	
	private void clearTextBoxError(int millis) {
		Timer t = new Timer(millis, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                textBoxError.setText(null);
            }
        });
        t.setRepeats(false);
        t.start();
	}
	
	private void issueErrorMsg(String msg) {
		textBoxError.setText("Error: " + msg);
		log.error(msg);
		clearTextBoxError(20000);
	}
	
	private void issueWarningMsg(String msg) {
		textBoxError.setText("Warning: " + msg);
		log.warning(msg);
		clearTextBoxError(10000);
	}
	
	private void setChangesUnsaved() {
		changesSaved = false;
		labelUnsavedChanges.setText("There are unsaved changes");
		
		TaskManager tm = TaskManager.getInstance();
		if (!tm.getTaskFile().equals("")) {
			buttonOverwriteTasks.setEnabled(true);
		}
	}
	
	private void setChangesSaved() {
		changesSaved = true;
		labelUnsavedChanges.setText("");
		buttonOverwriteTasks.setEnabled(false);
	}
	private boolean areChangesSaved() { return changesSaved; }
	
	private void overwriteChanges() {
		log.info("Saving tasks to disk");
		TaskManager tm = TaskManager.getInstance();
		tm.writeTasks(true);
		log.info("Tasks created/edited so far have been saved to disk");
		setChangesSaved();
	}
	
	private void saveChangesAs() {
		log.info("Choosing file for saving...");
		
		JFileChooser fc = new JFileChooser();
		File file;
		int returnVal = fc.showSaveDialog(jPanel3);
        if (returnVal != JFileChooser.APPROVE_OPTION) {
            log.info("Save command cancelled by user");
			return;
        }
		file = fc.getSelectedFile();
		String filename = file.getAbsolutePath();
		buttonOverwriteTasks.setEnabled(true);
		
		log.info("Saving to file '" + filename + "'");
		
		TaskManager tm = TaskManager.getInstance();
		boolean do_backup = true;
		if (!tm.getTaskFile().equals(filename)) {
			do_backup = false;
			tm.setTaskFile(filename);
		}
		tm.writeTasks(do_backup);
		setChangesSaved();
	}
	
	// assuming there are unsaved changes...
	private void promptSaveChanges() {
		String task_file = TaskManager.getInstance().getTaskFile();
		boolean save_as = false;
		if (task_file.equals("")) {
			log.info("There are unsaved changes that need to be stored in a file");
			save_as = true;
		}
		
		int response = JOptionPane.showConfirmDialog(
			null, "Do you want to save the changes?", "There are unsaved changes",
			JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE
		);
		
		boolean save = true;
		switch (response) {
			case JOptionPane.NO_OPTION:
			case JOptionPane.CLOSED_OPTION:
				save = false;
		}
		if (!save) {
			log.info("User does not want to save changes.... It's up to them...");
			return;
		}
		
		log.info("User wants to save changes");
		if (save_as) {
			log.info("Need a file");
			saveChangesAs();
			return;
		}
		overwriteChanges();
	}
	
	private String getPriority(DefaultMutableTreeNode n) {
		if (highPriorNode.isNodeDescendant(n)) { return "high"; }
		else if (medPriorNode.isNodeDescendant(n)) { return "med"; }
		else if (lowPriorNode.isNodeDescendant(n)) { return "low"; }
		issueErrorMsg("Could not determine priority of node");
		return "?";
	}
	
	private void refreshBoxesTask(Task t) {
		textBoxTaskName.setText(t.getName());
		labelTaskID.setText(t.getId());
		labelTaskState.setText(t.currentState().getState().toString());
		textBoxTaskDate.setText(t.getPrettyDate());
		textAreaTaskDescription.setText(t.getDescription());
		textAreaTaskChanges.setText(t.changesToString());
	}
	
	private void clearBoxesTask() {
		textAreaTaskDescription.setText("");
		labelTaskID.setText("000000");
		labelTaskState.setText("-");
		textAreaTaskChanges.setText("");
		textBoxTaskName.setText("");
		textBoxTaskDate.setText("");
	}
	
	private boolean treeHasSelection(String msg) {
		if (treeTasks.getSelectionCount() == 0) {
			issueErrorMsg(msg);
			return false;
		}
		return true;
	}
	
	private boolean treeHasSelection() {
		return treeTasks.getSelectionCount() > 0;
	}
	
    private void buttonClearMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonClearMouseClicked
        clearBoxesTask();
    }//GEN-LAST:event_buttonClearMouseClicked
	
    private void treeTasksValueChanged(TreeSelectionEvent evt) {//GEN-FIRST:event_treeTasksValueChanged
        if (!treeHasSelection()) { return; }
		DefaultMutableTreeNode sel
			= (DefaultMutableTreeNode) treeTasks.getLastSelectedPathComponent();
		if (sel.getLevel() <= 1) {
			// clear text boxes (nothing selected so nothing to show)
			clearBoxesTask();
			// disable edit button
			buttonEditTask.setEnabled(false);
			return;
		}
		Task node_task = (Task) sel.getUserObject();
		// fill in the text boxes
		refreshBoxesTask(node_task);
		// enable edit button
		buttonEditTask.setEnabled(true);
    }//GEN-LAST:event_treeTasksValueChanged

    private void buttonRemoveTaskMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonRemoveTaskMouseClicked
		if (!treeHasSelection("A task must be selected in order to delete it")) { return; }
		
		DefaultMutableTreeNode sel
			= (DefaultMutableTreeNode) treeTasks.getLastSelectedPathComponent();
		if (sel.getLevel() <= 1) {
			issueWarningMsg("You can't delete the root node or the high/med/low nodes");
			return;
		}
		
		TaskManager tm = TaskManager.getInstance();
		Task node_task = (Task) sel.getUserObject();
		boolean d = tm.deleteTask(node_task.getId());
		if (!d) {
			log.info("Attempted at removing a subtask from the task manager");
			log.info("    Subtasks are never added at the manager");
		}
		
		DefaultMutableTreeNode par_sel
			= (DefaultMutableTreeNode) treeTasks.getLastSelectedPathComponent();
		treeModel.removeNodeFromParent(sel);
		treeModel.reload(par_sel);
		setChangesUnsaved();
    }//GEN-LAST:event_buttonRemoveTaskMouseClicked

    private void buttonNewTaskMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonNewTaskMouseClicked
        if (treeTasks.getSelectionCount() == 0) {
			issueWarningMsg("A task can't be added if no category/task is selected.");
			return;
		}
		
		// prompt the user with an interface
		TaskGUI makeTask = new TaskGUI();
		Object[] button_options = {"Create task", "Cancel"};
		int res = JOptionPane.showOptionDialog(
			null, makeTask,
			"Create a new task",
			JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE,
			null, button_options, null
		);
		if (res != JOptionPane.OK_OPTION) {
			log.info("User cancelled creation of new task.");
			return;
		}
		
		// get data used to identify the task
		String task_name = makeTask.getTaskName();
		String task_descr = makeTask.getTaskDescription();
		
		log.info("New task:");
		log.info("    Name: " + task_name + ".");
		log.info("    Description: " + task_descr + ".");
		
		// find out if the task is high/med/low
		DefaultMutableTreeNode sel
			= (DefaultMutableTreeNode) treeTasks.getLastSelectedPathComponent();
		
		if (task_name.equals("")) {
			task_name = "Nameless task";
			log.info("No name for new task.");
		}
		if (task_descr.equals("")) {
			task_descr = "Empty task (yay! nothing to do!)";
			log.info("No description for new task.");
		}
		
		// create the task
		TaskManager tm = TaskManager.getInstance();
		Task new_t = tm.newTask(task_name, task_descr);
		
		// the task should only be added to the taks manager's
		// containers if they are children of the "high/med/low" nodes.
		if (sel.getLevel() == 1) {
			String prior = getPriority(sel);
			if (prior.equals("high")) { tm.insertHighTask(0, new_t); }
			else if (prior.equals("med")) { tm.insertMedTask(0, new_t); }
			else if (prior.equals("low")) { tm.insertLowTask(0, new_t); }
			else { return; }
		}
		
		// is this new task a subtask? the selection is a task,
		// so the new task is actually a subtask!
		if (sel.getLevel() > 1) {
			// the task associated to the selected node
			Task node_task = (Task) sel.getUserObject();
			// add the new task as a subtask
			node_task.addSubtask(new_t);
			// change state
			String m = "A subtask was added (id: " + new_t.getId() + ")";
			node_task.changeState(m, TaskStateEnum.AddedSubtask);
			// fill in the text boxes
			refreshBoxesTask(node_task);
		}
		
		// make the node so as to show it to the user
		DefaultMutableTreeNode new_node = new DefaultMutableTreeNode(new_t);
		sel.insert(new_node, 0);
		treeModel.reload(sel);
		treeTasks.expandPath(new TreePath(sel.getPath()));
		treeTasks.setSelectionPath(new TreePath(new_node.getPath()));
		setChangesUnsaved();
    }//GEN-LAST:event_buttonNewTaskMouseClicked

    private void buttonOverwriteTasksMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonOverwriteTasksMouseClicked
        overwriteChanges();
    }//GEN-LAST:event_buttonOverwriteTasksMouseClicked

	private void moveTaskUpDown(String dir, int incr) {
		if (!treeHasSelection("A task must be selected in order to move it")) { return; }
		DefaultMutableTreeNode sel
			= (DefaultMutableTreeNode) treeTasks.getLastSelectedPathComponent();
		if (sel.getLevel() <= 1) {
			issueWarningMsg("Can't move root node or nodes high/med/low.");
			return;
		}
		
		// the task associated to the node
		Task t = (Task) sel.getUserObject();
		
		log.info("Selected node (task id: '" + t.getId() + "' has level " + sel.getLevel() + ".");
		log.info("    Moving selection '" + dir + "' (by " + incr + ").");
		
		DefaultMutableTreeNode par_sel = (DefaultMutableTreeNode) sel.getParent();
		int idx = par_sel.getIndex(sel);
		if (dir.equals("up") && idx == 0) {
			issueWarningMsg("Can't increase priority of the highest-priority subtask.");
			return;
		}
		if (dir.equals("down") && idx == par_sel.getChildCount() - 1) {
			issueWarningMsg("Can't decrease priority of the lowest-priority subtask.");
			return;
		}
		
		log.info("    Selected node is the " + idx + "-th child of its parent.");
		
		// move the task inside the task manager
		if (sel.getLevel() == 2) {
			String prior = getPriority(sel);
			log.info("    Moving task of priority '" + prior + "' within the task manager.");
			TaskManager tm = TaskManager.getInstance();
			int i;
			if (prior.equals("high")) {
				i = tm.deleteHighTask(t.getId());
				tm.insertHighTask(i + incr, t);
			}
			else if (prior.equals("med")) {
				i = tm.deleteMedTask(t.getId());
				tm.insertMedTask(i + incr, t);
			}
			else if (prior.equals("low")) {
				i = tm.deleteLowTask(t.getId());
				tm.insertLowTask(i + incr, t);
			}
			else { return; }
			log.info("    Moved from position " + (i) + " to position " + (i + incr) + ".");
		}
		
		// if the task has a parent, move the subtask
		// within the parent's list of subtasks
		Task parent_task = t.getParent();
		if (parent_task != null) {
			log.info("    Moving task within the parent task's list of subtasks.");
			parent_task.moveSubtaskBy(t.getId(), incr);
		}
		
		// move the task in the tree
		treeModel.removeNodeFromParent(sel);
		par_sel.insert(sel, idx + incr);
		
		sel = (DefaultMutableTreeNode) par_sel.getChildAt(idx + incr);
		treeModel.reload(par_sel);
		treeTasks.expandPath(new TreePath(sel.getPath()));
		treeTasks.setSelectionPath(new TreePath(sel.getPath()));
		setChangesUnsaved();
	}
	
    private void buttonTaskUpMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonTaskUpMouseClicked
        moveTaskUpDown("up", -1);
    }//GEN-LAST:event_buttonTaskUpMouseClicked

    private void buttonTaskDownMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonTaskDownMouseClicked
        moveTaskUpDown("down", +1);
    }//GEN-LAST:event_buttonTaskDownMouseClicked

	private void changeTaskPriority(String dir, int incr) {
		if (!treeHasSelection("A task must be selected in order to move it")) {
			return;
		}
		DefaultMutableTreeNode sel
			= (DefaultMutableTreeNode) treeTasks.getLastSelectedPathComponent();
		if (sel.getLevel() < 0) { return; }
		if (sel.getLevel() <= 1) {
			issueWarningMsg("Can't move root node or nodes high/med/low.");
			return;
		}
		if (sel.getLevel() > 2) {
			issueWarningMsg("Can't change a task's priority if it is a subtask of another task.");
			return;
		}
		
		String cur_prior = getPriority(sel);
		if (dir.equals("incr") && cur_prior.equals("high")) {
			issueWarningMsg("Can't increase priority of a highest-priority task.");
			return;
		}
		if (dir.equals("decr") && cur_prior.equals("low")) {
			issueWarningMsg("Can't decrease priority of a lowest-priority task.");
			return;
		}
		
		Task t = (Task) sel.getUserObject();
		TaskManager tm = TaskManager.getInstance();
		
		DefaultMutableTreeNode from_prior = null;
		DefaultMutableTreeNode to_prior = null;
		String verb = "";
		String new_prior = "??";
		
		if (cur_prior.equals("high")) {
			from_prior = highPriorNode;
			to_prior = medPriorNode;
			new_prior = "med";
			verb = "Decreased";
		}
		else if (cur_prior.equals("med")) {
			from_prior = medPriorNode;
			if (dir.equals("incr")) {
				to_prior = highPriorNode;
				new_prior = "high";
				verb = "Increased";
			}
			else if (dir.equals("decr")) {
				to_prior = lowPriorNode;
				new_prior = "low";
				verb = "Decreased";
			}
		}
		else if (cur_prior.equals("low")) {
			from_prior = lowPriorNode;
			to_prior = medPriorNode;
			new_prior = "medium";
			verb = "Increased";
		}
		else { return; }
		
		from_prior.remove(sel);
		to_prior.insert(sel, 0);
		
		if (cur_prior.equals("high"))     { tm.deleteHighTask(t.getId()); }
		else if (cur_prior.equals("med")) { tm.deleteMedTask(t.getId()); }
		else if (cur_prior.equals("low")) { tm.deleteLowTask(t.getId()); }
		
		if (new_prior.equals("high"))     { tm.insertHighTask(0, t); }
		else if (new_prior.equals("med")) { tm.insertMedTask(0, t); }
		else if (new_prior.equals("low")) { tm.insertLowTask(0, t); }
		
		t.changeState(
			verb + " priority to " + new_prior + ".",
			TaskStateEnum.PriorityChanged
		);
		
		refreshBoxesTask(t);
		treeModel.reload(from_prior);
		treeModel.reload(to_prior);
		treeTasks.expandPath(new TreePath(from_prior.getPath()));
		treeTasks.expandPath(new TreePath(to_prior.getPath()));
		treeTasks.expandPath(new TreePath(sel.getPath()));
		treeTasks.setSelectionPath(new TreePath(sel.getPath()));
		setChangesUnsaved();
	}
	
    private void buttonIncrPriorityMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonIncrPriorityMouseClicked
        changeTaskPriority("incr", -1);
    }//GEN-LAST:event_buttonIncrPriorityMouseClicked

    private void buttonDecrPriorityMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonDecrPriorityMouseClicked
        changeTaskPriority("decr", +1);
    }//GEN-LAST:event_buttonDecrPriorityMouseClicked

	// 'n' is the parent of task 't'
	private void taskToNode(DefaultMutableTreeNode n, Task t) {
		// make a new node, with associated task
		DefaultMutableTreeNode new_node = new DefaultMutableTreeNode(t);
		// insert node
		n.insert(new_node, n.getChildCount());
		// insert subtasks
		t.getSubtasks().forEach((st) -> { taskToNode(new_node, st); });
	}
	
    private void menuItemOpenFileMousePressed(MouseEvent evt) {//GEN-FIRST:event_menuItemOpenFileMousePressed
		if (!areChangesSaved()) {
			promptSaveChanges();
		}
		
		log.info("Choosing file for opening...");
		
		JFileChooser fc = new JFileChooser();
		File file;
		int returnVal = fc.showOpenDialog(jPanel3);
        if (returnVal != JFileChooser.APPROVE_OPTION) {
            log.info("Open command cancelled by user.");
			return;
        }
		file = fc.getSelectedFile();
		String filename = file.getAbsolutePath();
		
		log.info("Opening file '" + filename + "'.");
		
		TaskManager tm = TaskManager.getInstance();
		tm.setTaskFile(filename);
		if (!tm.readTasks()) {
			issueErrorMsg("Could not open selected file '" + filename + "'.");
			return;
		}
		buttonOverwriteTasks.setEnabled(true);
		
		// clear tree...
		highPriorNode.removeAllChildren();
		medPriorNode.removeAllChildren();
		lowPriorNode.removeAllChildren();
		treeModel.reload();
		
		// fill tree...
		tm.getHighPriorTasks().forEach((t) -> { taskToNode(highPriorNode, t); });
		tm.getMedPriorTasks().forEach((t) -> { taskToNode(medPriorNode, t); });
		tm.getLowPriorTasks().forEach((t) -> { taskToNode(lowPriorNode, t); });
		treeModel.reload();
		setTreeExpandedState(true);
    }//GEN-LAST:event_menuItemOpenFileMousePressed

    private void buttonSaveTasksAsMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonSaveTasksAsMouseClicked
        saveChangesAs();
    }//GEN-LAST:event_buttonSaveTasksAsMouseClicked

    private void buttonEditTaskMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonEditTaskMouseClicked
        if (!treeHasSelection("A task must be selected in order to edit its name and description.")) {
			return;
		}
		DefaultMutableTreeNode sel
			= (DefaultMutableTreeNode) treeTasks.getLastSelectedPathComponent();
		
		if (sel.getLevel() == 1) {
			issueErrorMsg("The selection must be a task (not a priority list)!");
			return;
		}
		
		Task t = (Task) sel.getUserObject();
		// current task's name and description
		String prevName = t.getName();
		String prevDescr = t.getDescription();
		
		// prompt the user with an interface
		TaskGUI editTask = new TaskGUI();
		editTask.setTaskName(prevName);
		editTask.setTaskDescription(prevDescr);
		Object[] button_options = {"Save edits", "Cancel"};
		int res = JOptionPane.showOptionDialog(
			null, editTask,
			"Edit an already exiting task",
			JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE,
			null, button_options, null
		);
		if (res != JOptionPane.OK_OPTION) {
			log.info("User cancelled edition of task.");
			return;
		}

		// new name and description
		t.setName(editTask.getTaskName());
		t.setDescription(editTask.getTaskDescription());
		// set the change to the task
		t.taskWasEdited("Edited name and/or description.", prevName, prevDescr, TaskStateEnum.Edited);
		
		refreshBoxesTask(t);
		
		// this edit jhas been written to the task, but not to the file
		setChangesUnsaved();
    }//GEN-LAST:event_buttonEditTaskMouseClicked

	private void changeTaskState(TaskStateEnum s, String custom_reason, boolean use_reason)
	{
		if (!treeHasSelection("A task must be selected in order to change its state")) {
			return;
		}
		DefaultMutableTreeNode sel
			= (DefaultMutableTreeNode) treeTasks.getLastSelectedPathComponent();
		Task t = (Task) sel.getUserObject();
		String r = t.askChangeState(s);
		if (!r.equals("")) {
			issueErrorMsg("Can't change state of task (id: " + t.getId() + ") due to: " + r);
			return;
		}
		String reason;
		if (use_reason) { reason = custom_reason; }
		else {
			reason = JOptionPane.showInputDialog(
				null, "Why do you want to change the task's state?", "Change a task's state",
				JOptionPane.PLAIN_MESSAGE // no icon
			);
		}
		t.changeState(reason, s);
		refreshBoxesTask(t);
		treeModel.reload(sel);
		setChangesUnsaved();
	}
	
    private void buttonTaskDoneMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonTaskDoneMouseClicked
        changeTaskState(TaskStateEnum.Done, "The task has been completed.", true);
    }//GEN-LAST:event_buttonTaskDoneMouseClicked

    private void buttonTaskWorkingMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonTaskWorkingMouseClicked
        changeTaskState(TaskStateEnum.Working, "Working on it.", true);
    }//GEN-LAST:event_buttonTaskWorkingMouseClicked

    private void buttonTaskHoldMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonTaskHoldMouseClicked
        changeTaskState(TaskStateEnum.PutOnHold, "", false);
    }//GEN-LAST:event_buttonTaskHoldMouseClicked

    private void buttonTaskOnRevisionMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonTaskOnRevisionMouseClicked
        changeTaskState(TaskStateEnum.OnRevision, "The task is being revised.", true);
    }//GEN-LAST:event_buttonTaskOnRevisionMouseClicked

    private void buttonTaskPendingRevisionMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonTaskPendingRevisionMouseClicked
        changeTaskState(TaskStateEnum.PendingRevision, "", false);
    }//GEN-LAST:event_buttonTaskPendingRevisionMouseClicked

    private void buttonTaskCancelMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonTaskCancelMouseClicked
        changeTaskState(TaskStateEnum.Cancelled, "", false);
    }//GEN-LAST:event_buttonTaskCancelMouseClicked

    private void buttonTaskDeleteMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonTaskDeleteMouseClicked
        changeTaskState(TaskStateEnum.Deleted, "", false);
    }//GEN-LAST:event_buttonTaskDeleteMouseClicked

    private void menuItemAboutMousePressed(MouseEvent evt) {//GEN-FIRST:event_menuItemAboutMousePressed
        JOptionPane.showMessageDialog(null,
			"Todo List Manager\n\nCopyright 2019\n\nBy: Lluís Alemany Puig"
		);
    }//GEN-LAST:event_menuItemAboutMousePressed

    private void buttonExpandAllMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonExpandAllMouseClicked
        setTreeExpandedState(true);
    }//GEN-LAST:event_buttonExpandAllMouseClicked

    private void buttonContractAllMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonContractAllMouseClicked
        setTreeExpandedState(false);
    }//GEN-LAST:event_buttonContractAllMouseClicked

    private void formWindowClosing(WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (!areChangesSaved()) {
			promptSaveChanges();
		}
    }//GEN-LAST:event_formWindowClosing

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainView().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton buttonClear;
    private JButton buttonContractAll;
    private JButton buttonDecrPriority;
    private JButton buttonEditTask;
    private JButton buttonExpandAll;
    private JButton buttonIncrPriority;
    private JButton buttonNewTask;
    private JButton buttonOverwriteTasks;
    private JButton buttonRemoveTask;
    private JButton buttonSaveTasksAs;
    private JButton buttonTaskCancel;
    private JButton buttonTaskDelete;
    private JButton buttonTaskDone;
    private JButton buttonTaskDown;
    private JButton buttonTaskHold;
    private JButton buttonTaskOnRevision;
    private JButton buttonTaskPendingRevision;
    private JButton buttonTaskUp;
    private JButton buttonTaskWorking;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel6;
    private JMenu jMenu1;
    private JMenuBar jMenuBar1;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel5;
    private JPanel jPanel7;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane6;
    private JScrollPane jScrollPane7;
    private JLabel labelTaskID;
    private JLabel labelTaskState;
    private JLabel labelUnsavedChanges;
    private JMenuItem menuItemAbout;
    private JMenuItem menuItemOpenFile;
    private JTextArea textAreaTaskChanges;
    private JTextArea textAreaTaskDescription;
    private JTextField textBoxError;
    private JTextField textBoxTaskDate;
    private JTextField textBoxTaskName;
    private JTree treeTasks;
    // End of variables declaration//GEN-END:variables

}
